default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("DB_USERNAME", "inboxed") %>
  password: <%= ENV.fetch("DB_PASSWORD", "inboxed") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  primary:
    <<: *default
    database: inboxed_development
  queue:
    <<: *default
    database: inboxed_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: inboxed_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: inboxed_test
  queue:
    <<: *default
    database: inboxed_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: inboxed_test_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL") { ENV["DATABASE_URL"] } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL") { ENV["DATABASE_URL"] } %>
    migrations_paths: db/cable_migrate
